//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JavaScriptLexer.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class JavaScriptLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		MULTI_LINE_COMMENT=1, SINGLE_LINE_COMMENT=2, CONSOLE_LOG=3, VAR=4, OPEN_BRACE=5, 
		CLOSE_BRACE=6, ASSIGN=7, PLUS=8, MINUS=9, DIVIDE=10, MULTIPLY=11, OPEN_PAREN=12, 
		CLOSE_PAREN=13, LESS_THAN=14, MORE_THAN=15, LESS_THAN_EQUALS=16, GREATER_THAN_EQUALS=17, 
		EQUALS=18, NOT_EQUALS=19, IDENTITY_EQUALS=20, IDENTITY_NOT_EQUALS=21, 
		AND=22, OR=23, BOOLEAN=24, IF=25, ELSE=26, NUMBER=27, IDENTIFIER=28, STRING=29, 
		EOL=30, WHITE_SPACES=31;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"MULTI_LINE_COMMENT", "SINGLE_LINE_COMMENT", "CONSOLE_LOG", "VAR", "OPEN_BRACE", 
		"CLOSE_BRACE", "ASSIGN", "PLUS", "MINUS", "DIVIDE", "MULTIPLY", "OPEN_PAREN", 
		"CLOSE_PAREN", "LESS_THAN", "MORE_THAN", "LESS_THAN_EQUALS", "GREATER_THAN_EQUALS", 
		"EQUALS", "NOT_EQUALS", "IDENTITY_EQUALS", "IDENTITY_NOT_EQUALS", "AND", 
		"OR", "BOOLEAN", "IF", "ELSE", "NUMBER", "INTEGER_NUMBER", "IDENTIFIER", 
		"STRING", "DoubleStringCharacter", "SingleStringCharacter", "SingleEscapeCharacter", 
		"LineContinuation", "EOL", "WHITE_SPACES"
	};


	public JavaScriptLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public JavaScriptLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, "'console.log'", "'var'", "'{'", "'}'", "'='", "'+'", 
		"'-'", "'/'", "'*'", "'('", "')'", "'<'", "'>'", "'<='", "'>='", "'=='", 
		"'!='", "'==='", "'!=='", "'&&'", "'||'", null, "'if'", "'else'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "MULTI_LINE_COMMENT", "SINGLE_LINE_COMMENT", "CONSOLE_LOG", "VAR", 
		"OPEN_BRACE", "CLOSE_BRACE", "ASSIGN", "PLUS", "MINUS", "DIVIDE", "MULTIPLY", 
		"OPEN_PAREN", "CLOSE_PAREN", "LESS_THAN", "MORE_THAN", "LESS_THAN_EQUALS", 
		"GREATER_THAN_EQUALS", "EQUALS", "NOT_EQUALS", "IDENTITY_EQUALS", "IDENTITY_NOT_EQUALS", 
		"AND", "OR", "BOOLEAN", "IF", "ELSE", "NUMBER", "IDENTIFIER", "STRING", 
		"EOL", "WHITE_SPACES"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "JavaScriptLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static JavaScriptLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '!', '\x111', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\a', '\x2', 'P', '\n', '\x2', 
		'\f', '\x2', '\xE', '\x2', 'S', '\v', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\a', '\x3', '^', '\n', '\x3', '\f', '\x3', 
		'\xE', '\x3', '\x61', '\v', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x5', '\x19', '\xAE', '\n', '\x19', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1C', '\a', '\x1C', '\xBC', '\n', '\x1C', '\f', '\x1C', '\xE', '\x1C', 
		'\xBF', '\v', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\a', 
		'\x1C', '\xC4', '\n', '\x1C', '\f', '\x1C', '\xE', '\x1C', '\xC7', '\v', 
		'\x1C', '\x3', '\x1C', '\x5', '\x1C', '\xCA', '\n', '\x1C', '\x3', '\x1D', 
		'\x3', '\x1D', '\x3', '\x1D', '\a', '\x1D', '\xCF', '\n', '\x1D', '\f', 
		'\x1D', '\xE', '\x1D', '\xD2', '\v', '\x1D', '\x5', '\x1D', '\xD4', '\n', 
		'\x1D', '\x3', '\x1E', '\x3', '\x1E', '\a', '\x1E', '\xD8', '\n', '\x1E', 
		'\f', '\x1E', '\xE', '\x1E', '\xDB', '\v', '\x1E', '\x3', '\x1F', '\x3', 
		'\x1F', '\a', '\x1F', '\xDF', '\n', '\x1F', '\f', '\x1F', '\xE', '\x1F', 
		'\xE2', '\v', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\a', 
		'\x1F', '\xE7', '\n', '\x1F', '\f', '\x1F', '\xE', '\x1F', '\xEA', '\v', 
		'\x1F', '\x3', '\x1F', '\x5', '\x1F', '\xED', '\n', '\x1F', '\x3', ' ', 
		'\x3', ' ', '\x3', ' ', '\x3', ' ', '\x5', ' ', '\xF3', '\n', ' ', '\x3', 
		'!', '\x3', '!', '\x3', '!', '\x3', '!', '\x5', '!', '\xF9', '\n', '!', 
		'\x3', '\"', '\x3', '\"', '\x3', '#', '\x3', '#', '\x3', '#', '\x3', '$', 
		'\a', '$', '\x101', '\n', '$', '\f', '$', '\xE', '$', '\x104', '\v', '$', 
		'\x3', '$', '\x6', '$', '\x107', '\n', '$', '\r', '$', '\xE', '$', '\x108', 
		'\x3', '%', '\x6', '%', '\x10C', '\n', '%', '\r', '%', '\xE', '%', '\x10D', 
		'\x3', '%', '\x3', '%', '\x3', 'Q', '\x2', '&', '\x3', '\x3', '\x5', '\x4', 
		'\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', 
		'\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', 
		'\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', 
		'\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', 
		'\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', 
		'\x2', ';', '\x1E', '=', '\x1F', '?', '\x2', '\x41', '\x2', '\x43', '\x2', 
		'\x45', '\x2', 'G', ' ', 'I', '!', '\x3', '\x2', '\r', '\x5', '\x2', '\f', 
		'\f', '\xF', '\xF', '\x202A', '\x202B', '\x3', '\x2', '\x32', ';', '\x4', 
		'\x2', '\x32', ';', '\x61', '\x61', '\x3', '\x2', '\x33', ';', '\x5', 
		'\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', '\x32', 
		';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', '\f', '\f', 
		'\xF', '\xF', '$', '$', '^', '^', '\x6', '\x2', '\f', '\f', '\xF', '\xF', 
		')', ')', '^', '^', '\v', '\x2', '$', '$', ')', ')', '^', '^', '\x64', 
		'\x64', 'h', 'h', 'p', 'p', 't', 't', 'v', 'v', 'x', 'x', '\x3', '\x2', 
		'=', '=', '\x6', '\x2', '\v', '\v', '\r', '\xE', '\"', '\"', '\xA2', '\xA2', 
		'\x2', '\x11F', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', 'G', '\x3', 
		'\x2', '\x2', '\x2', '\x2', 'I', '\x3', '\x2', '\x2', '\x2', '\x3', 'K', 
		'\x3', '\x2', '\x2', '\x2', '\x5', 'Y', '\x3', '\x2', '\x2', '\x2', '\a', 
		'\x64', '\x3', '\x2', '\x2', '\x2', '\t', 'p', '\x3', '\x2', '\x2', '\x2', 
		'\v', 't', '\x3', '\x2', '\x2', '\x2', '\r', 'v', '\x3', '\x2', '\x2', 
		'\x2', '\xF', 'x', '\x3', '\x2', '\x2', '\x2', '\x11', 'z', '\x3', '\x2', 
		'\x2', '\x2', '\x13', '|', '\x3', '\x2', '\x2', '\x2', '\x15', '~', '\x3', 
		'\x2', '\x2', '\x2', '\x17', '\x80', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'\x82', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x84', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '\x86', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x88', '\x3', 
		'\x2', '\x2', '\x2', '!', '\x8A', '\x3', '\x2', '\x2', '\x2', '#', '\x8D', 
		'\x3', '\x2', '\x2', '\x2', '%', '\x90', '\x3', '\x2', '\x2', '\x2', '\'', 
		'\x93', '\x3', '\x2', '\x2', '\x2', ')', '\x96', '\x3', '\x2', '\x2', 
		'\x2', '+', '\x9A', '\x3', '\x2', '\x2', '\x2', '-', '\x9E', '\x3', '\x2', 
		'\x2', '\x2', '/', '\xA1', '\x3', '\x2', '\x2', '\x2', '\x31', '\xAD', 
		'\x3', '\x2', '\x2', '\x2', '\x33', '\xAF', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\xB2', '\x3', '\x2', '\x2', '\x2', '\x37', '\xC9', '\x3', '\x2', 
		'\x2', '\x2', '\x39', '\xD3', '\x3', '\x2', '\x2', '\x2', ';', '\xD5', 
		'\x3', '\x2', '\x2', '\x2', '=', '\xEC', '\x3', '\x2', '\x2', '\x2', '?', 
		'\xF2', '\x3', '\x2', '\x2', '\x2', '\x41', '\xF8', '\x3', '\x2', '\x2', 
		'\x2', '\x43', '\xFA', '\x3', '\x2', '\x2', '\x2', '\x45', '\xFC', '\x3', 
		'\x2', '\x2', '\x2', 'G', '\x102', '\x3', '\x2', '\x2', '\x2', 'I', '\x10B', 
		'\x3', '\x2', '\x2', '\x2', 'K', 'L', '\a', '\x31', '\x2', '\x2', 'L', 
		'M', '\a', ',', '\x2', '\x2', 'M', 'Q', '\x3', '\x2', '\x2', '\x2', 'N', 
		'P', '\v', '\x2', '\x2', '\x2', 'O', 'N', '\x3', '\x2', '\x2', '\x2', 
		'P', 'S', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\x3', '\x2', '\x2', '\x2', 
		'Q', 'O', '\x3', '\x2', '\x2', '\x2', 'R', 'T', '\x3', '\x2', '\x2', '\x2', 
		'S', 'Q', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\a', ',', '\x2', '\x2', 
		'U', 'V', '\a', '\x31', '\x2', '\x2', 'V', 'W', '\x3', '\x2', '\x2', '\x2', 
		'W', 'X', '\b', '\x2', '\x2', '\x2', 'X', '\x4', '\x3', '\x2', '\x2', 
		'\x2', 'Y', 'Z', '\a', '\x31', '\x2', '\x2', 'Z', '[', '\a', '\x31', '\x2', 
		'\x2', '[', '_', '\x3', '\x2', '\x2', '\x2', '\\', '^', '\n', '\x2', '\x2', 
		'\x2', ']', '\\', '\x3', '\x2', '\x2', '\x2', '^', '\x61', '\x3', '\x2', 
		'\x2', '\x2', '_', ']', '\x3', '\x2', '\x2', '\x2', '_', '`', '\x3', '\x2', 
		'\x2', '\x2', '`', '\x62', '\x3', '\x2', '\x2', '\x2', '\x61', '_', '\x3', 
		'\x2', '\x2', '\x2', '\x62', '\x63', '\b', '\x3', '\x2', '\x2', '\x63', 
		'\x6', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', '\x65', '\x2', 
		'\x2', '\x65', '\x66', '\a', 'q', '\x2', '\x2', '\x66', 'g', '\a', 'p', 
		'\x2', '\x2', 'g', 'h', '\a', 'u', '\x2', '\x2', 'h', 'i', '\a', 'q', 
		'\x2', '\x2', 'i', 'j', '\a', 'n', '\x2', '\x2', 'j', 'k', '\a', 'g', 
		'\x2', '\x2', 'k', 'l', '\a', '\x30', '\x2', '\x2', 'l', 'm', '\a', 'n', 
		'\x2', '\x2', 'm', 'n', '\a', 'q', '\x2', '\x2', 'n', 'o', '\a', 'i', 
		'\x2', '\x2', 'o', '\b', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', 'x', 
		'\x2', '\x2', 'q', 'r', '\a', '\x63', '\x2', '\x2', 'r', 's', '\a', 't', 
		'\x2', '\x2', 's', '\n', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', '}', 
		'\x2', '\x2', 'u', '\f', '\x3', '\x2', '\x2', '\x2', 'v', 'w', '\a', '\x7F', 
		'\x2', '\x2', 'w', '\xE', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\a', 
		'?', '\x2', '\x2', 'y', '\x10', '\x3', '\x2', '\x2', '\x2', 'z', '{', 
		'\a', '-', '\x2', '\x2', '{', '\x12', '\x3', '\x2', '\x2', '\x2', '|', 
		'}', '\a', '/', '\x2', '\x2', '}', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'~', '\x7F', '\a', '\x31', '\x2', '\x2', '\x7F', '\x16', '\x3', '\x2', 
		'\x2', '\x2', '\x80', '\x81', '\a', ',', '\x2', '\x2', '\x81', '\x18', 
		'\x3', '\x2', '\x2', '\x2', '\x82', '\x83', '\a', '*', '\x2', '\x2', '\x83', 
		'\x1A', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\a', '+', '\x2', 
		'\x2', '\x85', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\a', 
		'>', '\x2', '\x2', '\x87', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x88', 
		'\x89', '\a', '@', '\x2', '\x2', '\x89', ' ', '\x3', '\x2', '\x2', '\x2', 
		'\x8A', '\x8B', '\a', '>', '\x2', '\x2', '\x8B', '\x8C', '\a', '?', '\x2', 
		'\x2', '\x8C', '\"', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', '\a', 
		'@', '\x2', '\x2', '\x8E', '\x8F', '\a', '?', '\x2', '\x2', '\x8F', '$', 
		'\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\a', '?', '\x2', '\x2', '\x91', 
		'\x92', '\a', '?', '\x2', '\x2', '\x92', '&', '\x3', '\x2', '\x2', '\x2', 
		'\x93', '\x94', '\a', '#', '\x2', '\x2', '\x94', '\x95', '\a', '?', '\x2', 
		'\x2', '\x95', '(', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\a', 
		'?', '\x2', '\x2', '\x97', '\x98', '\a', '?', '\x2', '\x2', '\x98', '\x99', 
		'\a', '?', '\x2', '\x2', '\x99', '*', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x9B', '\a', '#', '\x2', '\x2', '\x9B', '\x9C', '\a', '?', '\x2', '\x2', 
		'\x9C', '\x9D', '\a', '?', '\x2', '\x2', '\x9D', ',', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\x9F', '\a', '(', '\x2', '\x2', '\x9F', '\xA0', '\a', 
		'(', '\x2', '\x2', '\xA0', '.', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', 
		'\a', '~', '\x2', '\x2', '\xA2', '\xA3', '\a', '~', '\x2', '\x2', '\xA3', 
		'\x30', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\a', 'v', '\x2', 
		'\x2', '\xA5', '\xA6', '\a', 't', '\x2', '\x2', '\xA6', '\xA7', '\a', 
		'w', '\x2', '\x2', '\xA7', '\xAE', '\a', 'g', '\x2', '\x2', '\xA8', '\xA9', 
		'\a', 'h', '\x2', '\x2', '\xA9', '\xAA', '\a', '\x63', '\x2', '\x2', '\xAA', 
		'\xAB', '\a', 'n', '\x2', '\x2', '\xAB', '\xAC', '\a', 'u', '\x2', '\x2', 
		'\xAC', '\xAE', '\a', 'g', '\x2', '\x2', '\xAD', '\xA4', '\x3', '\x2', 
		'\x2', '\x2', '\xAD', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xAE', '\x32', 
		'\x3', '\x2', '\x2', '\x2', '\xAF', '\xB0', '\a', 'k', '\x2', '\x2', '\xB0', 
		'\xB1', '\a', 'h', '\x2', '\x2', '\xB1', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '\xB2', '\xB3', '\a', 'g', '\x2', '\x2', '\xB3', '\xB4', '\a', 
		'n', '\x2', '\x2', '\xB4', '\xB5', '\a', 'u', '\x2', '\x2', '\xB5', '\xB6', 
		'\a', 'g', '\x2', '\x2', '\xB6', '\x36', '\x3', '\x2', '\x2', '\x2', '\xB7', 
		'\xB8', '\x5', '\x39', '\x1D', '\x2', '\xB8', '\xB9', '\a', '\x30', '\x2', 
		'\x2', '\xB9', '\xBD', '\t', '\x3', '\x2', '\x2', '\xBA', '\xBC', '\t', 
		'\x4', '\x2', '\x2', '\xBB', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xBC', 
		'\xBF', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xBB', '\x3', '\x2', '\x2', 
		'\x2', '\xBD', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xCA', '\x3', 
		'\x2', '\x2', '\x2', '\xBF', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xC0', 
		'\xC1', '\a', '\x30', '\x2', '\x2', '\xC1', '\xC5', '\t', '\x3', '\x2', 
		'\x2', '\xC2', '\xC4', '\t', '\x4', '\x2', '\x2', '\xC3', '\xC2', '\x3', 
		'\x2', '\x2', '\x2', '\xC4', '\xC7', '\x3', '\x2', '\x2', '\x2', '\xC5', 
		'\xC3', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC6', '\x3', '\x2', '\x2', 
		'\x2', '\xC6', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC5', '\x3', 
		'\x2', '\x2', '\x2', '\xC8', '\xCA', '\x5', '\x39', '\x1D', '\x2', '\xC9', 
		'\xB7', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xC0', '\x3', '\x2', '\x2', 
		'\x2', '\xC9', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xCA', '\x38', '\x3', 
		'\x2', '\x2', '\x2', '\xCB', '\xD4', '\a', '\x32', '\x2', '\x2', '\xCC', 
		'\xD0', '\t', '\x5', '\x2', '\x2', '\xCD', '\xCF', '\t', '\x4', '\x2', 
		'\x2', '\xCE', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD2', '\x3', 
		'\x2', '\x2', '\x2', '\xD0', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xD0', 
		'\xD1', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xD4', '\x3', '\x2', '\x2', 
		'\x2', '\xD2', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xCB', '\x3', 
		'\x2', '\x2', '\x2', '\xD3', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xD4', 
		':', '\x3', '\x2', '\x2', '\x2', '\xD5', '\xD9', '\t', '\x6', '\x2', '\x2', 
		'\xD6', '\xD8', '\t', '\a', '\x2', '\x2', '\xD7', '\xD6', '\x3', '\x2', 
		'\x2', '\x2', '\xD8', '\xDB', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xD7', 
		'\x3', '\x2', '\x2', '\x2', '\xD9', '\xDA', '\x3', '\x2', '\x2', '\x2', 
		'\xDA', '<', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xD9', '\x3', '\x2', 
		'\x2', '\x2', '\xDC', '\xE0', '\a', '$', '\x2', '\x2', '\xDD', '\xDF', 
		'\x5', '?', ' ', '\x2', '\xDE', '\xDD', '\x3', '\x2', '\x2', '\x2', '\xDF', 
		'\xE2', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xDE', '\x3', '\x2', '\x2', 
		'\x2', '\xE0', '\xE1', '\x3', '\x2', '\x2', '\x2', '\xE1', '\xE3', '\x3', 
		'\x2', '\x2', '\x2', '\xE2', '\xE0', '\x3', '\x2', '\x2', '\x2', '\xE3', 
		'\xED', '\a', '$', '\x2', '\x2', '\xE4', '\xE8', '\a', ')', '\x2', '\x2', 
		'\xE5', '\xE7', '\x5', '\x41', '!', '\x2', '\xE6', '\xE5', '\x3', '\x2', 
		'\x2', '\x2', '\xE7', '\xEA', '\x3', '\x2', '\x2', '\x2', '\xE8', '\xE6', 
		'\x3', '\x2', '\x2', '\x2', '\xE8', '\xE9', '\x3', '\x2', '\x2', '\x2', 
		'\xE9', '\xEB', '\x3', '\x2', '\x2', '\x2', '\xEA', '\xE8', '\x3', '\x2', 
		'\x2', '\x2', '\xEB', '\xED', '\a', ')', '\x2', '\x2', '\xEC', '\xDC', 
		'\x3', '\x2', '\x2', '\x2', '\xEC', '\xE4', '\x3', '\x2', '\x2', '\x2', 
		'\xED', '>', '\x3', '\x2', '\x2', '\x2', '\xEE', '\xF3', '\n', '\b', '\x2', 
		'\x2', '\xEF', '\xF0', '\a', '^', '\x2', '\x2', '\xF0', '\xF3', '\x5', 
		'\x43', '\"', '\x2', '\xF1', '\xF3', '\x5', '\x45', '#', '\x2', '\xF2', 
		'\xEE', '\x3', '\x2', '\x2', '\x2', '\xF2', '\xEF', '\x3', '\x2', '\x2', 
		'\x2', '\xF2', '\xF1', '\x3', '\x2', '\x2', '\x2', '\xF3', '@', '\x3', 
		'\x2', '\x2', '\x2', '\xF4', '\xF9', '\n', '\t', '\x2', '\x2', '\xF5', 
		'\xF6', '\a', '^', '\x2', '\x2', '\xF6', '\xF9', '\x5', '\x43', '\"', 
		'\x2', '\xF7', '\xF9', '\x5', '\x45', '#', '\x2', '\xF8', '\xF4', '\x3', 
		'\x2', '\x2', '\x2', '\xF8', '\xF5', '\x3', '\x2', '\x2', '\x2', '\xF8', 
		'\xF7', '\x3', '\x2', '\x2', '\x2', '\xF9', '\x42', '\x3', '\x2', '\x2', 
		'\x2', '\xFA', '\xFB', '\t', '\n', '\x2', '\x2', '\xFB', '\x44', '\x3', 
		'\x2', '\x2', '\x2', '\xFC', '\xFD', '\a', '^', '\x2', '\x2', '\xFD', 
		'\xFE', '\t', '\x2', '\x2', '\x2', '\xFE', '\x46', '\x3', '\x2', '\x2', 
		'\x2', '\xFF', '\x101', '\t', '\v', '\x2', '\x2', '\x100', '\xFF', '\x3', 
		'\x2', '\x2', '\x2', '\x101', '\x104', '\x3', '\x2', '\x2', '\x2', '\x102', 
		'\x100', '\x3', '\x2', '\x2', '\x2', '\x102', '\x103', '\x3', '\x2', '\x2', 
		'\x2', '\x103', '\x106', '\x3', '\x2', '\x2', '\x2', '\x104', '\x102', 
		'\x3', '\x2', '\x2', '\x2', '\x105', '\x107', '\t', '\x2', '\x2', '\x2', 
		'\x106', '\x105', '\x3', '\x2', '\x2', '\x2', '\x107', '\x108', '\x3', 
		'\x2', '\x2', '\x2', '\x108', '\x106', '\x3', '\x2', '\x2', '\x2', '\x108', 
		'\x109', '\x3', '\x2', '\x2', '\x2', '\x109', 'H', '\x3', '\x2', '\x2', 
		'\x2', '\x10A', '\x10C', '\t', '\f', '\x2', '\x2', '\x10B', '\x10A', '\x3', 
		'\x2', '\x2', '\x2', '\x10C', '\x10D', '\x3', '\x2', '\x2', '\x2', '\x10D', 
		'\x10B', '\x3', '\x2', '\x2', '\x2', '\x10D', '\x10E', '\x3', '\x2', '\x2', 
		'\x2', '\x10E', '\x10F', '\x3', '\x2', '\x2', '\x2', '\x10F', '\x110', 
		'\b', '%', '\x2', '\x2', '\x110', 'J', '\x3', '\x2', '\x2', '\x2', '\x14', 
		'\x2', 'Q', '_', '\xAD', '\xBD', '\xC5', '\xC9', '\xD0', '\xD3', '\xD9', 
		'\xE0', '\xE8', '\xEC', '\xF2', '\xF8', '\x102', '\x108', '\x10D', '\x3', 
		'\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
