//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JavaScriptParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class JavaScriptParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		MULTI_LINE_COMMENT=1, SINGLE_LINE_COMMENT=2, CONSOLE_LOG=3, VAR=4, CONTINUE=5, 
		FOR=6, WHILE=7, OPEN_BRACKET=8, CLOSE_BRACKET=9, OPEN_BRACE=10, CLOSE_BRACE=11, 
		COMMA=12, SEMI_COLON=13, ASSIGN=14, PLUS=15, MINUS=16, DIVIDE=17, MULTIPLY=18, 
		OPEN_PAREN=19, CLOSE_PAREN=20, LESS_THAN=21, MORE_THAN=22, LESS_THAN_EQUALS=23, 
		GREATER_THAN_EQUALS=24, EQUALS=25, NOT_EQUALS=26, IDENTITY_EQUALS=27, 
		IDENTITY_NOT_EQUALS=28, AND=29, OR=30, BOOLEAN=31, IF=32, ELSE=33, NUMBER=34, 
		IDENTIFIER=35, STRING=36, EOL=37, WHITE_SPACES=38;
	public const int
		RULE_parse = 0, RULE_instructions = 1, RULE_instructionLine = 2, RULE_instruction = 3, 
		RULE_instructionBlock = 4, RULE_writeStdOutput = 5, RULE_writeStdOutputConstant = 6, 
		RULE_writeStdOutputIdentifier = 7, RULE_writeStdOutputArithmeticOperation = 8, 
		RULE_arithmeticOperation = 9, RULE_arithmeticOperationHigher = 10, RULE_conditionOperation = 11, 
		RULE_arithmeticAdditiveSign = 12, RULE_arithmeticMultiplpicativeSign = 13, 
		RULE_value = 14, RULE_constantValue = 15, RULE_booleanValue = 16, RULE_stringValue = 17, 
		RULE_numberValue = 18, RULE_identifierValue = 19, RULE_variableDeclaratiion = 20, 
		RULE_conditionSign = 21, RULE_assignOperation = 22, RULE_assignValue = 23, 
		RULE_singleExpression = 24, RULE_ifStatement = 25, RULE_ifStatementConditionOperation = 26, 
		RULE_elseStatement = 27, RULE_loops = 28, RULE_whileLoop = 29, RULE_whileStatementConditionOperation = 30, 
		RULE_forLoop = 31, RULE_forStatementConditionOperation = 32, RULE_forExpression = 33, 
		RULE_arrayLiteral = 34, RULE_elementList = 35, RULE_arrayElement = 36;
	public static readonly string[] ruleNames = {
		"parse", "instructions", "instructionLine", "instruction", "instructionBlock", 
		"writeStdOutput", "writeStdOutputConstant", "writeStdOutputIdentifier", 
		"writeStdOutputArithmeticOperation", "arithmeticOperation", "arithmeticOperationHigher", 
		"conditionOperation", "arithmeticAdditiveSign", "arithmeticMultiplpicativeSign", 
		"value", "constantValue", "booleanValue", "stringValue", "numberValue", 
		"identifierValue", "variableDeclaratiion", "conditionSign", "assignOperation", 
		"assignValue", "singleExpression", "ifStatement", "ifStatementConditionOperation", 
		"elseStatement", "loops", "whileLoop", "whileStatementConditionOperation", 
		"forLoop", "forStatementConditionOperation", "forExpression", "arrayLiteral", 
		"elementList", "arrayElement"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, "'console.log'", "'var'", "'continue'", "'for'", "'while'", 
		"'['", "']'", "'{'", "'}'", "','", "';'", "'='", "'+'", "'-'", "'/'", 
		"'*'", "'('", "')'", "'<'", "'>'", "'<='", "'>='", "'=='", "'!='", "'==='", 
		"'!=='", "'&&'", "'||'", null, "'if'", "'else'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "MULTI_LINE_COMMENT", "SINGLE_LINE_COMMENT", "CONSOLE_LOG", "VAR", 
		"CONTINUE", "FOR", "WHILE", "OPEN_BRACKET", "CLOSE_BRACKET", "OPEN_BRACE", 
		"CLOSE_BRACE", "COMMA", "SEMI_COLON", "ASSIGN", "PLUS", "MINUS", "DIVIDE", 
		"MULTIPLY", "OPEN_PAREN", "CLOSE_PAREN", "LESS_THAN", "MORE_THAN", "LESS_THAN_EQUALS", 
		"GREATER_THAN_EQUALS", "EQUALS", "NOT_EQUALS", "IDENTITY_EQUALS", "IDENTITY_NOT_EQUALS", 
		"AND", "OR", "BOOLEAN", "IF", "ELSE", "NUMBER", "IDENTIFIER", "STRING", 
		"EOL", "WHITE_SPACES"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "JavaScriptParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static JavaScriptParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public JavaScriptParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public JavaScriptParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ParseContext : ParserRuleContext {
		public InstructionsContext[] instructions() {
			return GetRuleContexts<InstructionsContext>();
		}
		public InstructionsContext instructions(int i) {
			return GetRuleContext<InstructionsContext>(i);
		}
		public ITerminalNode Eof() { return GetToken(JavaScriptParser.Eof, 0); }
		public ParseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parse; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterParse(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitParse(this);
		}
	}

	[RuleVersion(0)]
	public ParseContext parse() {
		ParseContext _localctx = new ParseContext(Context, State);
		EnterRule(_localctx, 0, RULE_parse);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 77;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << CONSOLE_LOG) | (1L << VAR) | (1L << FOR) | (1L << WHILE) | (1L << IF) | (1L << IDENTIFIER))) != 0)) {
				{
				{
				State = 74; instructions();
				}
				}
				State = 79;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 81;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				{
				State = 80; Match(Eof);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstructionsContext : ParserRuleContext {
		public InstructionLineContext[] instructionLine() {
			return GetRuleContexts<InstructionLineContext>();
		}
		public InstructionLineContext instructionLine(int i) {
			return GetRuleContext<InstructionLineContext>(i);
		}
		public InstructionsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instructions; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterInstructions(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitInstructions(this);
		}
	}

	[RuleVersion(0)]
	public InstructionsContext instructions() {
		InstructionsContext _localctx = new InstructionsContext(Context, State);
		EnterRule(_localctx, 2, RULE_instructions);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 84;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 83; instructionLine();
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 86;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstructionLineContext : ParserRuleContext {
		public InstructionContext instruction() {
			return GetRuleContext<InstructionContext>(0);
		}
		public ITerminalNode EOL() { return GetToken(JavaScriptParser.EOL, 0); }
		public InstructionLineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instructionLine; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterInstructionLine(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitInstructionLine(this);
		}
	}

	[RuleVersion(0)]
	public InstructionLineContext instructionLine() {
		InstructionLineContext _localctx = new InstructionLineContext(Context, State);
		EnterRule(_localctx, 4, RULE_instructionLine);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88; instruction();
			State = 89; Match(EOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstructionContext : ParserRuleContext {
		public VariableDeclaratiionContext variableDeclaratiion() {
			return GetRuleContext<VariableDeclaratiionContext>(0);
		}
		public AssignOperationContext assignOperation() {
			return GetRuleContext<AssignOperationContext>(0);
		}
		public WriteStdOutputContext writeStdOutput() {
			return GetRuleContext<WriteStdOutputContext>(0);
		}
		public IfStatementContext ifStatement() {
			return GetRuleContext<IfStatementContext>(0);
		}
		public LoopsContext loops() {
			return GetRuleContext<LoopsContext>(0);
		}
		public InstructionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterInstruction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitInstruction(this);
		}
	}

	[RuleVersion(0)]
	public InstructionContext instruction() {
		InstructionContext _localctx = new InstructionContext(Context, State);
		EnterRule(_localctx, 6, RULE_instruction);
		try {
			State = 96;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 91; variableDeclaratiion();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 92; assignOperation();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 93; writeStdOutput();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 94; ifStatement();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 95; loops();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstructionBlockContext : ParserRuleContext {
		public ITerminalNode OPEN_BRACE() { return GetToken(JavaScriptParser.OPEN_BRACE, 0); }
		public InstructionsContext instructions() {
			return GetRuleContext<InstructionsContext>(0);
		}
		public ITerminalNode CLOSE_BRACE() { return GetToken(JavaScriptParser.CLOSE_BRACE, 0); }
		public ITerminalNode[] EOL() { return GetTokens(JavaScriptParser.EOL); }
		public ITerminalNode EOL(int i) {
			return GetToken(JavaScriptParser.EOL, i);
		}
		public InstructionBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instructionBlock; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterInstructionBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitInstructionBlock(this);
		}
	}

	[RuleVersion(0)]
	public InstructionBlockContext instructionBlock() {
		InstructionBlockContext _localctx = new InstructionBlockContext(Context, State);
		EnterRule(_localctx, 8, RULE_instructionBlock);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 101;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==EOL) {
				{
				{
				State = 98; Match(EOL);
				}
				}
				State = 103;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 104; Match(OPEN_BRACE);
			State = 108;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==EOL) {
				{
				{
				State = 105; Match(EOL);
				}
				}
				State = 110;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 111; instructions();
			State = 115;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==EOL) {
				{
				{
				State = 112; Match(EOL);
				}
				}
				State = 117;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 118; Match(CLOSE_BRACE);
			State = 122;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 119; Match(EOL);
					}
					} 
				}
				State = 124;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WriteStdOutputContext : ParserRuleContext {
		public WriteStdOutputConstantContext writeStdOutputConstant() {
			return GetRuleContext<WriteStdOutputConstantContext>(0);
		}
		public WriteStdOutputIdentifierContext writeStdOutputIdentifier() {
			return GetRuleContext<WriteStdOutputIdentifierContext>(0);
		}
		public WriteStdOutputArithmeticOperationContext writeStdOutputArithmeticOperation() {
			return GetRuleContext<WriteStdOutputArithmeticOperationContext>(0);
		}
		public WriteStdOutputContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_writeStdOutput; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterWriteStdOutput(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitWriteStdOutput(this);
		}
	}

	[RuleVersion(0)]
	public WriteStdOutputContext writeStdOutput() {
		WriteStdOutputContext _localctx = new WriteStdOutputContext(Context, State);
		EnterRule(_localctx, 10, RULE_writeStdOutput);
		try {
			State = 128;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 125; writeStdOutputConstant();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 126; writeStdOutputIdentifier();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 127; writeStdOutputArithmeticOperation();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WriteStdOutputConstantContext : ParserRuleContext {
		public ITerminalNode CONSOLE_LOG() { return GetToken(JavaScriptParser.CONSOLE_LOG, 0); }
		public ITerminalNode OPEN_PAREN() { return GetToken(JavaScriptParser.OPEN_PAREN, 0); }
		public ConstantValueContext constantValue() {
			return GetRuleContext<ConstantValueContext>(0);
		}
		public ITerminalNode CLOSE_PAREN() { return GetToken(JavaScriptParser.CLOSE_PAREN, 0); }
		public WriteStdOutputConstantContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_writeStdOutputConstant; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterWriteStdOutputConstant(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitWriteStdOutputConstant(this);
		}
	}

	[RuleVersion(0)]
	public WriteStdOutputConstantContext writeStdOutputConstant() {
		WriteStdOutputConstantContext _localctx = new WriteStdOutputConstantContext(Context, State);
		EnterRule(_localctx, 12, RULE_writeStdOutputConstant);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 130; Match(CONSOLE_LOG);
			State = 131; Match(OPEN_PAREN);
			State = 132; constantValue();
			State = 133; Match(CLOSE_PAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WriteStdOutputIdentifierContext : ParserRuleContext {
		public ITerminalNode CONSOLE_LOG() { return GetToken(JavaScriptParser.CONSOLE_LOG, 0); }
		public ITerminalNode OPEN_PAREN() { return GetToken(JavaScriptParser.OPEN_PAREN, 0); }
		public IdentifierValueContext identifierValue() {
			return GetRuleContext<IdentifierValueContext>(0);
		}
		public ITerminalNode CLOSE_PAREN() { return GetToken(JavaScriptParser.CLOSE_PAREN, 0); }
		public WriteStdOutputIdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_writeStdOutputIdentifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterWriteStdOutputIdentifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitWriteStdOutputIdentifier(this);
		}
	}

	[RuleVersion(0)]
	public WriteStdOutputIdentifierContext writeStdOutputIdentifier() {
		WriteStdOutputIdentifierContext _localctx = new WriteStdOutputIdentifierContext(Context, State);
		EnterRule(_localctx, 14, RULE_writeStdOutputIdentifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 135; Match(CONSOLE_LOG);
			State = 136; Match(OPEN_PAREN);
			State = 137; identifierValue();
			State = 138; Match(CLOSE_PAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WriteStdOutputArithmeticOperationContext : ParserRuleContext {
		public ITerminalNode CONSOLE_LOG() { return GetToken(JavaScriptParser.CONSOLE_LOG, 0); }
		public ITerminalNode OPEN_PAREN() { return GetToken(JavaScriptParser.OPEN_PAREN, 0); }
		public ArithmeticOperationContext arithmeticOperation() {
			return GetRuleContext<ArithmeticOperationContext>(0);
		}
		public ITerminalNode CLOSE_PAREN() { return GetToken(JavaScriptParser.CLOSE_PAREN, 0); }
		public WriteStdOutputArithmeticOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_writeStdOutputArithmeticOperation; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterWriteStdOutputArithmeticOperation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitWriteStdOutputArithmeticOperation(this);
		}
	}

	[RuleVersion(0)]
	public WriteStdOutputArithmeticOperationContext writeStdOutputArithmeticOperation() {
		WriteStdOutputArithmeticOperationContext _localctx = new WriteStdOutputArithmeticOperationContext(Context, State);
		EnterRule(_localctx, 16, RULE_writeStdOutputArithmeticOperation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 140; Match(CONSOLE_LOG);
			State = 141; Match(OPEN_PAREN);
			State = 142; arithmeticOperation(0);
			State = 143; Match(CLOSE_PAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArithmeticOperationContext : ParserRuleContext {
		public ArithmeticOperationHigherContext arithmeticOperationHigher() {
			return GetRuleContext<ArithmeticOperationHigherContext>(0);
		}
		public ArithmeticOperationContext arithmeticOperation() {
			return GetRuleContext<ArithmeticOperationContext>(0);
		}
		public ArithmeticAdditiveSignContext arithmeticAdditiveSign() {
			return GetRuleContext<ArithmeticAdditiveSignContext>(0);
		}
		public ArithmeticOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arithmeticOperation; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterArithmeticOperation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitArithmeticOperation(this);
		}
	}

	[RuleVersion(0)]
	public ArithmeticOperationContext arithmeticOperation() {
		return arithmeticOperation(0);
	}

	private ArithmeticOperationContext arithmeticOperation(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ArithmeticOperationContext _localctx = new ArithmeticOperationContext(Context, _parentState);
		ArithmeticOperationContext _prevctx = _localctx;
		int _startState = 18;
		EnterRecursionRule(_localctx, 18, RULE_arithmeticOperation, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 146; arithmeticOperationHigher(0);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 154;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new ArithmeticOperationContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_arithmeticOperation);
					State = 148;
					if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
					State = 149; arithmeticAdditiveSign();
					State = 150; arithmeticOperationHigher(0);
					}
					} 
				}
				State = 156;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ArithmeticOperationHigherContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ArithmeticOperationHigherContext arithmeticOperationHigher() {
			return GetRuleContext<ArithmeticOperationHigherContext>(0);
		}
		public ArithmeticMultiplpicativeSignContext arithmeticMultiplpicativeSign() {
			return GetRuleContext<ArithmeticMultiplpicativeSignContext>(0);
		}
		public ArithmeticOperationHigherContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arithmeticOperationHigher; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterArithmeticOperationHigher(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitArithmeticOperationHigher(this);
		}
	}

	[RuleVersion(0)]
	public ArithmeticOperationHigherContext arithmeticOperationHigher() {
		return arithmeticOperationHigher(0);
	}

	private ArithmeticOperationHigherContext arithmeticOperationHigher(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ArithmeticOperationHigherContext _localctx = new ArithmeticOperationHigherContext(Context, _parentState);
		ArithmeticOperationHigherContext _prevctx = _localctx;
		int _startState = 20;
		EnterRecursionRule(_localctx, 20, RULE_arithmeticOperationHigher, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 158; value();
			}
			Context.Stop = TokenStream.LT(-1);
			State = 166;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new ArithmeticOperationHigherContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_arithmeticOperationHigher);
					State = 160;
					if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
					State = 161; arithmeticMultiplpicativeSign();
					State = 162; value();
					}
					} 
				}
				State = 168;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ConditionOperationContext : ParserRuleContext {
		public ArithmeticOperationContext arithmeticOperation() {
			return GetRuleContext<ArithmeticOperationContext>(0);
		}
		public ConditionSignContext conditionSign() {
			return GetRuleContext<ConditionSignContext>(0);
		}
		public ConditionOperationContext conditionOperation() {
			return GetRuleContext<ConditionOperationContext>(0);
		}
		public ConditionOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_conditionOperation; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterConditionOperation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitConditionOperation(this);
		}
	}

	[RuleVersion(0)]
	public ConditionOperationContext conditionOperation() {
		ConditionOperationContext _localctx = new ConditionOperationContext(Context, State);
		EnterRule(_localctx, 22, RULE_conditionOperation);
		try {
			State = 174;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 169; arithmeticOperation(0);
				State = 170; conditionSign();
				State = 171; conditionOperation();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 173; arithmeticOperation(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArithmeticAdditiveSignContext : ParserRuleContext {
		public ITerminalNode PLUS() { return GetToken(JavaScriptParser.PLUS, 0); }
		public ITerminalNode MINUS() { return GetToken(JavaScriptParser.MINUS, 0); }
		public ArithmeticAdditiveSignContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arithmeticAdditiveSign; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterArithmeticAdditiveSign(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitArithmeticAdditiveSign(this);
		}
	}

	[RuleVersion(0)]
	public ArithmeticAdditiveSignContext arithmeticAdditiveSign() {
		ArithmeticAdditiveSignContext _localctx = new ArithmeticAdditiveSignContext(Context, State);
		EnterRule(_localctx, 24, RULE_arithmeticAdditiveSign);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 176;
			_la = TokenStream.LA(1);
			if ( !(_la==PLUS || _la==MINUS) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArithmeticMultiplpicativeSignContext : ParserRuleContext {
		public ITerminalNode MULTIPLY() { return GetToken(JavaScriptParser.MULTIPLY, 0); }
		public ITerminalNode DIVIDE() { return GetToken(JavaScriptParser.DIVIDE, 0); }
		public ArithmeticMultiplpicativeSignContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arithmeticMultiplpicativeSign; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterArithmeticMultiplpicativeSign(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitArithmeticMultiplpicativeSign(this);
		}
	}

	[RuleVersion(0)]
	public ArithmeticMultiplpicativeSignContext arithmeticMultiplpicativeSign() {
		ArithmeticMultiplpicativeSignContext _localctx = new ArithmeticMultiplpicativeSignContext(Context, State);
		EnterRule(_localctx, 26, RULE_arithmeticMultiplpicativeSign);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 178;
			_la = TokenStream.LA(1);
			if ( !(_la==DIVIDE || _la==MULTIPLY) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		public ConstantValueContext constantValue() {
			return GetRuleContext<ConstantValueContext>(0);
		}
		public IdentifierValueContext identifierValue() {
			return GetRuleContext<IdentifierValueContext>(0);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 28, RULE_value);
		try {
			State = 182;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BOOLEAN:
			case NUMBER:
			case STRING:
				EnterOuterAlt(_localctx, 1);
				{
				State = 180; constantValue();
				}
				break;
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 181; identifierValue();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstantValueContext : ParserRuleContext {
		public BooleanValueContext booleanValue() {
			return GetRuleContext<BooleanValueContext>(0);
		}
		public StringValueContext stringValue() {
			return GetRuleContext<StringValueContext>(0);
		}
		public NumberValueContext numberValue() {
			return GetRuleContext<NumberValueContext>(0);
		}
		public ConstantValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constantValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterConstantValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitConstantValue(this);
		}
	}

	[RuleVersion(0)]
	public ConstantValueContext constantValue() {
		ConstantValueContext _localctx = new ConstantValueContext(Context, State);
		EnterRule(_localctx, 30, RULE_constantValue);
		try {
			State = 187;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BOOLEAN:
				EnterOuterAlt(_localctx, 1);
				{
				State = 184; booleanValue();
				}
				break;
			case STRING:
				EnterOuterAlt(_localctx, 2);
				{
				State = 185; stringValue();
				}
				break;
			case NUMBER:
				EnterOuterAlt(_localctx, 3);
				{
				State = 186; numberValue();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BooleanValueContext : ParserRuleContext {
		public ITerminalNode BOOLEAN() { return GetToken(JavaScriptParser.BOOLEAN, 0); }
		public BooleanValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_booleanValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterBooleanValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitBooleanValue(this);
		}
	}

	[RuleVersion(0)]
	public BooleanValueContext booleanValue() {
		BooleanValueContext _localctx = new BooleanValueContext(Context, State);
		EnterRule(_localctx, 32, RULE_booleanValue);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 189; Match(BOOLEAN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringValueContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(JavaScriptParser.STRING, 0); }
		public StringValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stringValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterStringValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitStringValue(this);
		}
	}

	[RuleVersion(0)]
	public StringValueContext stringValue() {
		StringValueContext _localctx = new StringValueContext(Context, State);
		EnterRule(_localctx, 34, RULE_stringValue);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 191; Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberValueContext : ParserRuleContext {
		public ITerminalNode NUMBER() { return GetToken(JavaScriptParser.NUMBER, 0); }
		public NumberValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numberValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterNumberValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitNumberValue(this);
		}
	}

	[RuleVersion(0)]
	public NumberValueContext numberValue() {
		NumberValueContext _localctx = new NumberValueContext(Context, State);
		EnterRule(_localctx, 36, RULE_numberValue);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 193; Match(NUMBER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierValueContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(JavaScriptParser.IDENTIFIER, 0); }
		public IdentifierValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifierValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterIdentifierValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitIdentifierValue(this);
		}
	}

	[RuleVersion(0)]
	public IdentifierValueContext identifierValue() {
		IdentifierValueContext _localctx = new IdentifierValueContext(Context, State);
		EnterRule(_localctx, 38, RULE_identifierValue);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 195; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableDeclaratiionContext : ParserRuleContext {
		public ITerminalNode VAR() { return GetToken(JavaScriptParser.VAR, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(JavaScriptParser.IDENTIFIER, 0); }
		public VariableDeclaratiionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableDeclaratiion; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterVariableDeclaratiion(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitVariableDeclaratiion(this);
		}
	}

	[RuleVersion(0)]
	public VariableDeclaratiionContext variableDeclaratiion() {
		VariableDeclaratiionContext _localctx = new VariableDeclaratiionContext(Context, State);
		EnterRule(_localctx, 40, RULE_variableDeclaratiion);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 197; Match(VAR);
			State = 198; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionSignContext : ParserRuleContext {
		public ITerminalNode LESS_THAN() { return GetToken(JavaScriptParser.LESS_THAN, 0); }
		public ITerminalNode MORE_THAN() { return GetToken(JavaScriptParser.MORE_THAN, 0); }
		public ITerminalNode LESS_THAN_EQUALS() { return GetToken(JavaScriptParser.LESS_THAN_EQUALS, 0); }
		public ITerminalNode GREATER_THAN_EQUALS() { return GetToken(JavaScriptParser.GREATER_THAN_EQUALS, 0); }
		public ITerminalNode EQUALS() { return GetToken(JavaScriptParser.EQUALS, 0); }
		public ITerminalNode NOT_EQUALS() { return GetToken(JavaScriptParser.NOT_EQUALS, 0); }
		public ITerminalNode IDENTITY_EQUALS() { return GetToken(JavaScriptParser.IDENTITY_EQUALS, 0); }
		public ITerminalNode IDENTITY_NOT_EQUALS() { return GetToken(JavaScriptParser.IDENTITY_NOT_EQUALS, 0); }
		public ConditionSignContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_conditionSign; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterConditionSign(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitConditionSign(this);
		}
	}

	[RuleVersion(0)]
	public ConditionSignContext conditionSign() {
		ConditionSignContext _localctx = new ConditionSignContext(Context, State);
		EnterRule(_localctx, 42, RULE_conditionSign);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 200;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LESS_THAN) | (1L << MORE_THAN) | (1L << LESS_THAN_EQUALS) | (1L << GREATER_THAN_EQUALS) | (1L << EQUALS) | (1L << NOT_EQUALS) | (1L << IDENTITY_EQUALS) | (1L << IDENTITY_NOT_EQUALS))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignOperationContext : ParserRuleContext {
		public VariableDeclaratiionContext variableDeclaratiion() {
			return GetRuleContext<VariableDeclaratiionContext>(0);
		}
		public ITerminalNode ASSIGN() { return GetToken(JavaScriptParser.ASSIGN, 0); }
		public AssignValueContext assignValue() {
			return GetRuleContext<AssignValueContext>(0);
		}
		public IdentifierValueContext identifierValue() {
			return GetRuleContext<IdentifierValueContext>(0);
		}
		public AssignOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignOperation; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterAssignOperation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitAssignOperation(this);
		}
	}

	[RuleVersion(0)]
	public AssignOperationContext assignOperation() {
		AssignOperationContext _localctx = new AssignOperationContext(Context, State);
		EnterRule(_localctx, 44, RULE_assignOperation);
		try {
			State = 210;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case VAR:
				EnterOuterAlt(_localctx, 1);
				{
				State = 202; variableDeclaratiion();
				State = 203; Match(ASSIGN);
				State = 204; assignValue();
				}
				break;
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 206; identifierValue();
				State = 207; Match(ASSIGN);
				State = 208; assignValue();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignValueContext : ParserRuleContext {
		public SingleExpressionContext singleExpression() {
			return GetRuleContext<SingleExpressionContext>(0);
		}
		public ArrayLiteralContext arrayLiteral() {
			return GetRuleContext<ArrayLiteralContext>(0);
		}
		public AssignValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterAssignValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitAssignValue(this);
		}
	}

	[RuleVersion(0)]
	public AssignValueContext assignValue() {
		AssignValueContext _localctx = new AssignValueContext(Context, State);
		EnterRule(_localctx, 46, RULE_assignValue);
		try {
			State = 214;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BOOLEAN:
			case NUMBER:
			case IDENTIFIER:
			case STRING:
				EnterOuterAlt(_localctx, 1);
				{
				State = 212; singleExpression();
				}
				break;
			case OPEN_BRACKET:
				EnterOuterAlt(_localctx, 2);
				{
				State = 213; arrayLiteral();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SingleExpressionContext : ParserRuleContext {
		public ArithmeticOperationContext arithmeticOperation() {
			return GetRuleContext<ArithmeticOperationContext>(0);
		}
		public ConditionOperationContext conditionOperation() {
			return GetRuleContext<ConditionOperationContext>(0);
		}
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public SingleExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_singleExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterSingleExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitSingleExpression(this);
		}
	}

	[RuleVersion(0)]
	public SingleExpressionContext singleExpression() {
		SingleExpressionContext _localctx = new SingleExpressionContext(Context, State);
		EnterRule(_localctx, 48, RULE_singleExpression);
		try {
			State = 219;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 216; arithmeticOperation(0);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 217; conditionOperation();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 218; value();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfStatementContext : ParserRuleContext {
		public ITerminalNode IF() { return GetToken(JavaScriptParser.IF, 0); }
		public ITerminalNode OPEN_PAREN() { return GetToken(JavaScriptParser.OPEN_PAREN, 0); }
		public IfStatementConditionOperationContext ifStatementConditionOperation() {
			return GetRuleContext<IfStatementConditionOperationContext>(0);
		}
		public ITerminalNode CLOSE_PAREN() { return GetToken(JavaScriptParser.CLOSE_PAREN, 0); }
		public InstructionBlockContext instructionBlock() {
			return GetRuleContext<InstructionBlockContext>(0);
		}
		public ElseStatementContext elseStatement() {
			return GetRuleContext<ElseStatementContext>(0);
		}
		public IfStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterIfStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitIfStatement(this);
		}
	}

	[RuleVersion(0)]
	public IfStatementContext ifStatement() {
		IfStatementContext _localctx = new IfStatementContext(Context, State);
		EnterRule(_localctx, 50, RULE_ifStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 221; Match(IF);
			State = 222; Match(OPEN_PAREN);
			State = 223; ifStatementConditionOperation();
			State = 224; Match(CLOSE_PAREN);
			State = 225; instructionBlock();
			State = 227;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ELSE) {
				{
				State = 226; elseStatement();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfStatementConditionOperationContext : ParserRuleContext {
		public ConditionOperationContext conditionOperation() {
			return GetRuleContext<ConditionOperationContext>(0);
		}
		public IfStatementConditionOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifStatementConditionOperation; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterIfStatementConditionOperation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitIfStatementConditionOperation(this);
		}
	}

	[RuleVersion(0)]
	public IfStatementConditionOperationContext ifStatementConditionOperation() {
		IfStatementConditionOperationContext _localctx = new IfStatementConditionOperationContext(Context, State);
		EnterRule(_localctx, 52, RULE_ifStatementConditionOperation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 229; conditionOperation();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElseStatementContext : ParserRuleContext {
		public ITerminalNode ELSE() { return GetToken(JavaScriptParser.ELSE, 0); }
		public InstructionBlockContext instructionBlock() {
			return GetRuleContext<InstructionBlockContext>(0);
		}
		public ElseStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elseStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterElseStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitElseStatement(this);
		}
	}

	[RuleVersion(0)]
	public ElseStatementContext elseStatement() {
		ElseStatementContext _localctx = new ElseStatementContext(Context, State);
		EnterRule(_localctx, 54, RULE_elseStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 231; Match(ELSE);
			State = 232; instructionBlock();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LoopsContext : ParserRuleContext {
		public WhileLoopContext whileLoop() {
			return GetRuleContext<WhileLoopContext>(0);
		}
		public ForLoopContext forLoop() {
			return GetRuleContext<ForLoopContext>(0);
		}
		public LoopsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_loops; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterLoops(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitLoops(this);
		}
	}

	[RuleVersion(0)]
	public LoopsContext loops() {
		LoopsContext _localctx = new LoopsContext(Context, State);
		EnterRule(_localctx, 56, RULE_loops);
		try {
			State = 236;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case WHILE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 234; whileLoop();
				}
				break;
			case FOR:
				EnterOuterAlt(_localctx, 2);
				{
				State = 235; forLoop();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhileLoopContext : ParserRuleContext {
		public ITerminalNode WHILE() { return GetToken(JavaScriptParser.WHILE, 0); }
		public ITerminalNode OPEN_PAREN() { return GetToken(JavaScriptParser.OPEN_PAREN, 0); }
		public WhileStatementConditionOperationContext whileStatementConditionOperation() {
			return GetRuleContext<WhileStatementConditionOperationContext>(0);
		}
		public ITerminalNode CLOSE_PAREN() { return GetToken(JavaScriptParser.CLOSE_PAREN, 0); }
		public InstructionBlockContext instructionBlock() {
			return GetRuleContext<InstructionBlockContext>(0);
		}
		public WhileLoopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_whileLoop; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterWhileLoop(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitWhileLoop(this);
		}
	}

	[RuleVersion(0)]
	public WhileLoopContext whileLoop() {
		WhileLoopContext _localctx = new WhileLoopContext(Context, State);
		EnterRule(_localctx, 58, RULE_whileLoop);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 238; Match(WHILE);
			State = 239; Match(OPEN_PAREN);
			State = 240; whileStatementConditionOperation();
			State = 241; Match(CLOSE_PAREN);
			State = 242; instructionBlock();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhileStatementConditionOperationContext : ParserRuleContext {
		public ConditionOperationContext conditionOperation() {
			return GetRuleContext<ConditionOperationContext>(0);
		}
		public WhileStatementConditionOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_whileStatementConditionOperation; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterWhileStatementConditionOperation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitWhileStatementConditionOperation(this);
		}
	}

	[RuleVersion(0)]
	public WhileStatementConditionOperationContext whileStatementConditionOperation() {
		WhileStatementConditionOperationContext _localctx = new WhileStatementConditionOperationContext(Context, State);
		EnterRule(_localctx, 60, RULE_whileStatementConditionOperation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 244; conditionOperation();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForLoopContext : ParserRuleContext {
		public ITerminalNode FOR() { return GetToken(JavaScriptParser.FOR, 0); }
		public ITerminalNode OPEN_PAREN() { return GetToken(JavaScriptParser.OPEN_PAREN, 0); }
		public ITerminalNode[] SEMI_COLON() { return GetTokens(JavaScriptParser.SEMI_COLON); }
		public ITerminalNode SEMI_COLON(int i) {
			return GetToken(JavaScriptParser.SEMI_COLON, i);
		}
		public ForStatementConditionOperationContext forStatementConditionOperation() {
			return GetRuleContext<ForStatementConditionOperationContext>(0);
		}
		public ITerminalNode CLOSE_PAREN() { return GetToken(JavaScriptParser.CLOSE_PAREN, 0); }
		public InstructionBlockContext instructionBlock() {
			return GetRuleContext<InstructionBlockContext>(0);
		}
		public AssignOperationContext assignOperation() {
			return GetRuleContext<AssignOperationContext>(0);
		}
		public ForExpressionContext forExpression() {
			return GetRuleContext<ForExpressionContext>(0);
		}
		public ForLoopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_forLoop; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterForLoop(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitForLoop(this);
		}
	}

	[RuleVersion(0)]
	public ForLoopContext forLoop() {
		ForLoopContext _localctx = new ForLoopContext(Context, State);
		EnterRule(_localctx, 62, RULE_forLoop);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 246; Match(FOR);
			State = 247; Match(OPEN_PAREN);
			State = 249;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==VAR || _la==IDENTIFIER) {
				{
				State = 248; assignOperation();
				}
			}

			State = 251; Match(SEMI_COLON);
			State = 252; forStatementConditionOperation();
			State = 253; Match(SEMI_COLON);
			State = 255;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==IDENTIFIER) {
				{
				State = 254; forExpression();
				}
			}

			State = 257; Match(CLOSE_PAREN);
			State = 258; instructionBlock();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForStatementConditionOperationContext : ParserRuleContext {
		public ConditionOperationContext conditionOperation() {
			return GetRuleContext<ConditionOperationContext>(0);
		}
		public ForStatementConditionOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_forStatementConditionOperation; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterForStatementConditionOperation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitForStatementConditionOperation(this);
		}
	}

	[RuleVersion(0)]
	public ForStatementConditionOperationContext forStatementConditionOperation() {
		ForStatementConditionOperationContext _localctx = new ForStatementConditionOperationContext(Context, State);
		EnterRule(_localctx, 64, RULE_forStatementConditionOperation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 260; conditionOperation();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForExpressionContext : ParserRuleContext {
		public IdentifierValueContext identifierValue() {
			return GetRuleContext<IdentifierValueContext>(0);
		}
		public ITerminalNode ASSIGN() { return GetToken(JavaScriptParser.ASSIGN, 0); }
		public AssignValueContext assignValue() {
			return GetRuleContext<AssignValueContext>(0);
		}
		public ForExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_forExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterForExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitForExpression(this);
		}
	}

	[RuleVersion(0)]
	public ForExpressionContext forExpression() {
		ForExpressionContext _localctx = new ForExpressionContext(Context, State);
		EnterRule(_localctx, 66, RULE_forExpression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 262; identifierValue();
			State = 263; Match(ASSIGN);
			State = 264; assignValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayLiteralContext : ParserRuleContext {
		public ITerminalNode OPEN_BRACKET() { return GetToken(JavaScriptParser.OPEN_BRACKET, 0); }
		public ElementListContext elementList() {
			return GetRuleContext<ElementListContext>(0);
		}
		public ITerminalNode CLOSE_BRACKET() { return GetToken(JavaScriptParser.CLOSE_BRACKET, 0); }
		public ArrayLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arrayLiteral; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterArrayLiteral(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitArrayLiteral(this);
		}
	}

	[RuleVersion(0)]
	public ArrayLiteralContext arrayLiteral() {
		ArrayLiteralContext _localctx = new ArrayLiteralContext(Context, State);
		EnterRule(_localctx, 68, RULE_arrayLiteral);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 266; Match(OPEN_BRACKET);
			State = 267; elementList();
			State = 268; Match(CLOSE_BRACKET);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElementListContext : ParserRuleContext {
		public ITerminalNode[] COMMA() { return GetTokens(JavaScriptParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(JavaScriptParser.COMMA, i);
		}
		public ArrayElementContext[] arrayElement() {
			return GetRuleContexts<ArrayElementContext>();
		}
		public ArrayElementContext arrayElement(int i) {
			return GetRuleContext<ArrayElementContext>(i);
		}
		public ElementListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elementList; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterElementList(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitElementList(this);
		}
	}

	[RuleVersion(0)]
	public ElementListContext elementList() {
		ElementListContext _localctx = new ElementListContext(Context, State);
		EnterRule(_localctx, 70, RULE_elementList);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 273;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,21,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 270; Match(COMMA);
					}
					} 
				}
				State = 275;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,21,Context);
			}
			State = 277;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << BOOLEAN) | (1L << NUMBER) | (1L << IDENTIFIER) | (1L << STRING))) != 0)) {
				{
				State = 276; arrayElement();
				}
			}

			State = 287;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,24,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 280;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					do {
						{
						{
						State = 279; Match(COMMA);
						}
						}
						State = 282;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					} while ( _la==COMMA );
					State = 284; arrayElement();
					}
					} 
				}
				State = 289;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,24,Context);
			}
			State = 293;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 290; Match(COMMA);
				}
				}
				State = 295;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayElementContext : ParserRuleContext {
		public SingleExpressionContext singleExpression() {
			return GetRuleContext<SingleExpressionContext>(0);
		}
		public ArrayElementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arrayElement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.EnterArrayElement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJavaScriptParserListener typedListener = listener as IJavaScriptParserListener;
			if (typedListener != null) typedListener.ExitArrayElement(this);
		}
	}

	[RuleVersion(0)]
	public ArrayElementContext arrayElement() {
		ArrayElementContext _localctx = new ArrayElementContext(Context, State);
		EnterRule(_localctx, 72, RULE_arrayElement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 296; singleExpression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 9: return arithmeticOperation_sempred((ArithmeticOperationContext)_localctx, predIndex);
		case 10: return arithmeticOperationHigher_sempred((ArithmeticOperationHigherContext)_localctx, predIndex);
		}
		return true;
	}
	private bool arithmeticOperation_sempred(ArithmeticOperationContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 2);
		}
		return true;
	}
	private bool arithmeticOperationHigher_sempred(ArithmeticOperationHigherContext _localctx, int predIndex) {
		switch (predIndex) {
		case 1: return Precpred(Context, 2);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '(', '\x12D', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x3', '\x2', '\a', '\x2', 'N', '\n', '\x2', '\f', '\x2', '\xE', 
		'\x2', 'Q', '\v', '\x2', '\x3', '\x2', '\x5', '\x2', 'T', '\n', '\x2', 
		'\x3', '\x3', '\x6', '\x3', 'W', '\n', '\x3', '\r', '\x3', '\xE', '\x3', 
		'X', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', '\x63', '\n', 
		'\x5', '\x3', '\x6', '\a', '\x6', '\x66', '\n', '\x6', '\f', '\x6', '\xE', 
		'\x6', 'i', '\v', '\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', 'm', 
		'\n', '\x6', '\f', '\x6', '\xE', '\x6', 'p', '\v', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\a', '\x6', 't', '\n', '\x6', '\f', '\x6', '\xE', '\x6', 
		'w', '\v', '\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', '{', '\n', 
		'\x6', '\f', '\x6', '\xE', '\x6', '~', '\v', '\x6', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x5', '\a', '\x83', '\n', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\a', '\v', '\x9B', 
		'\n', '\v', '\f', '\v', '\xE', '\v', '\x9E', '\v', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\a', '\f', '\xA7', '\n', '\f', '\f', '\f', '\xE', '\f', '\xAA', 
		'\v', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x5', '\r', '\xB1', '\n', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x5', '\x10', '\xB9', 
		'\n', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', '\x11', 
		'\xBE', '\n', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x5', '\x18', '\xD5', '\n', '\x18', 
		'\x3', '\x19', '\x3', '\x19', '\x5', '\x19', '\xD9', '\n', '\x19', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x5', '\x1A', '\xDE', '\n', '\x1A', 
		'\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', 
		'\x3', '\x1B', '\x5', '\x1B', '\xE6', '\n', '\x1B', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', 
		'\x1E', '\x5', '\x1E', '\xEF', '\n', '\x1E', '\x3', '\x1F', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', 
		'\x3', ' ', '\x3', '!', '\x3', '!', '\x3', '!', '\x5', '!', '\xFC', '\n', 
		'!', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', '!', '\x5', '!', '\x102', 
		'\n', '!', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', '\"', '\x3', '\"', 
		'\x3', '#', '\x3', '#', '\x3', '#', '\x3', '#', '\x3', '$', '\x3', '$', 
		'\x3', '$', '\x3', '$', '\x3', '%', '\a', '%', '\x112', '\n', '%', '\f', 
		'%', '\xE', '%', '\x115', '\v', '%', '\x3', '%', '\x5', '%', '\x118', 
		'\n', '%', '\x3', '%', '\x6', '%', '\x11B', '\n', '%', '\r', '%', '\xE', 
		'%', '\x11C', '\x3', '%', '\a', '%', '\x120', '\n', '%', '\f', '%', '\xE', 
		'%', '\x123', '\v', '%', '\x3', '%', '\a', '%', '\x126', '\n', '%', '\f', 
		'%', '\xE', '%', '\x129', '\v', '%', '\x3', '&', '\x3', '&', '\x3', '&', 
		'\x2', '\x4', '\x14', '\x16', '\'', '\x2', '\x4', '\x6', '\b', '\n', '\f', 
		'\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', 
		' ', '\"', '$', '&', '(', '*', ',', '.', '\x30', '\x32', '\x34', '\x36', 
		'\x38', ':', '<', '>', '@', '\x42', '\x44', '\x46', 'H', 'J', '\x2', '\x5', 
		'\x3', '\x2', '\x11', '\x12', '\x3', '\x2', '\x13', '\x14', '\x3', '\x2', 
		'\x17', '\x1E', '\x2', '\x127', '\x2', 'O', '\x3', '\x2', '\x2', '\x2', 
		'\x4', 'V', '\x3', '\x2', '\x2', '\x2', '\x6', 'Z', '\x3', '\x2', '\x2', 
		'\x2', '\b', '\x62', '\x3', '\x2', '\x2', '\x2', '\n', 'g', '\x3', '\x2', 
		'\x2', '\x2', '\f', '\x82', '\x3', '\x2', '\x2', '\x2', '\xE', '\x84', 
		'\x3', '\x2', '\x2', '\x2', '\x10', '\x89', '\x3', '\x2', '\x2', '\x2', 
		'\x12', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x14', '\x93', '\x3', '\x2', 
		'\x2', '\x2', '\x16', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x18', '\xB0', 
		'\x3', '\x2', '\x2', '\x2', '\x1A', '\xB2', '\x3', '\x2', '\x2', '\x2', 
		'\x1C', '\xB4', '\x3', '\x2', '\x2', '\x2', '\x1E', '\xB8', '\x3', '\x2', 
		'\x2', '\x2', ' ', '\xBD', '\x3', '\x2', '\x2', '\x2', '\"', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', '$', '\xC1', '\x3', '\x2', '\x2', '\x2', '&', '\xC3', 
		'\x3', '\x2', '\x2', '\x2', '(', '\xC5', '\x3', '\x2', '\x2', '\x2', '*', 
		'\xC7', '\x3', '\x2', '\x2', '\x2', ',', '\xCA', '\x3', '\x2', '\x2', 
		'\x2', '.', '\xD4', '\x3', '\x2', '\x2', '\x2', '\x30', '\xD8', '\x3', 
		'\x2', '\x2', '\x2', '\x32', '\xDD', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\xDF', '\x3', '\x2', '\x2', '\x2', '\x36', '\xE7', '\x3', '\x2', '\x2', 
		'\x2', '\x38', '\xE9', '\x3', '\x2', '\x2', '\x2', ':', '\xEE', '\x3', 
		'\x2', '\x2', '\x2', '<', '\xF0', '\x3', '\x2', '\x2', '\x2', '>', '\xF6', 
		'\x3', '\x2', '\x2', '\x2', '@', '\xF8', '\x3', '\x2', '\x2', '\x2', '\x42', 
		'\x106', '\x3', '\x2', '\x2', '\x2', '\x44', '\x108', '\x3', '\x2', '\x2', 
		'\x2', '\x46', '\x10C', '\x3', '\x2', '\x2', '\x2', 'H', '\x113', '\x3', 
		'\x2', '\x2', '\x2', 'J', '\x12A', '\x3', '\x2', '\x2', '\x2', 'L', 'N', 
		'\x5', '\x4', '\x3', '\x2', 'M', 'L', '\x3', '\x2', '\x2', '\x2', 'N', 
		'Q', '\x3', '\x2', '\x2', '\x2', 'O', 'M', '\x3', '\x2', '\x2', '\x2', 
		'O', 'P', '\x3', '\x2', '\x2', '\x2', 'P', 'S', '\x3', '\x2', '\x2', '\x2', 
		'Q', 'O', '\x3', '\x2', '\x2', '\x2', 'R', 'T', '\a', '\x2', '\x2', '\x3', 
		'S', 'R', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\x3', '\x2', '\x2', '\x2', 
		'T', '\x3', '\x3', '\x2', '\x2', '\x2', 'U', 'W', '\x5', '\x6', '\x4', 
		'\x2', 'V', 'U', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\x3', '\x2', '\x2', 
		'\x2', 'X', 'V', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\x3', '\x2', '\x2', 
		'\x2', 'Y', '\x5', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\x5', '\b', 
		'\x5', '\x2', '[', '\\', '\a', '\'', '\x2', '\x2', '\\', '\a', '\x3', 
		'\x2', '\x2', '\x2', ']', '\x63', '\x5', '*', '\x16', '\x2', '^', '\x63', 
		'\x5', '.', '\x18', '\x2', '_', '\x63', '\x5', '\f', '\a', '\x2', '`', 
		'\x63', '\x5', '\x34', '\x1B', '\x2', '\x61', '\x63', '\x5', ':', '\x1E', 
		'\x2', '\x62', ']', '\x3', '\x2', '\x2', '\x2', '\x62', '^', '\x3', '\x2', 
		'\x2', '\x2', '\x62', '_', '\x3', '\x2', '\x2', '\x2', '\x62', '`', '\x3', 
		'\x2', '\x2', '\x2', '\x62', '\x61', '\x3', '\x2', '\x2', '\x2', '\x63', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x64', '\x66', '\a', '\'', '\x2', '\x2', 
		'\x65', '\x64', '\x3', '\x2', '\x2', '\x2', '\x66', 'i', '\x3', '\x2', 
		'\x2', '\x2', 'g', '\x65', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\x3', 
		'\x2', '\x2', '\x2', 'h', 'j', '\x3', '\x2', '\x2', '\x2', 'i', 'g', '\x3', 
		'\x2', '\x2', '\x2', 'j', 'n', '\a', '\f', '\x2', '\x2', 'k', 'm', '\a', 
		'\'', '\x2', '\x2', 'l', 'k', '\x3', '\x2', '\x2', '\x2', 'm', 'p', '\x3', 
		'\x2', '\x2', '\x2', 'n', 'l', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\x3', 
		'\x2', '\x2', '\x2', 'o', 'q', '\x3', '\x2', '\x2', '\x2', 'p', 'n', '\x3', 
		'\x2', '\x2', '\x2', 'q', 'u', '\x5', '\x4', '\x3', '\x2', 'r', 't', '\a', 
		'\'', '\x2', '\x2', 's', 'r', '\x3', '\x2', '\x2', '\x2', 't', 'w', '\x3', 
		'\x2', '\x2', '\x2', 'u', 's', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\x3', 
		'\x2', '\x2', '\x2', 'v', 'x', '\x3', '\x2', '\x2', '\x2', 'w', 'u', '\x3', 
		'\x2', '\x2', '\x2', 'x', '|', '\a', '\r', '\x2', '\x2', 'y', '{', '\a', 
		'\'', '\x2', '\x2', 'z', 'y', '\x3', '\x2', '\x2', '\x2', '{', '~', '\x3', 
		'\x2', '\x2', '\x2', '|', 'z', '\x3', '\x2', '\x2', '\x2', '|', '}', '\x3', 
		'\x2', '\x2', '\x2', '}', '\v', '\x3', '\x2', '\x2', '\x2', '~', '|', 
		'\x3', '\x2', '\x2', '\x2', '\x7F', '\x83', '\x5', '\xE', '\b', '\x2', 
		'\x80', '\x83', '\x5', '\x10', '\t', '\x2', '\x81', '\x83', '\x5', '\x12', 
		'\n', '\x2', '\x82', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x82', '\x80', 
		'\x3', '\x2', '\x2', '\x2', '\x82', '\x81', '\x3', '\x2', '\x2', '\x2', 
		'\x83', '\r', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\a', '\x5', 
		'\x2', '\x2', '\x85', '\x86', '\a', '\x15', '\x2', '\x2', '\x86', '\x87', 
		'\x5', ' ', '\x11', '\x2', '\x87', '\x88', '\a', '\x16', '\x2', '\x2', 
		'\x88', '\xF', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\a', '\x5', 
		'\x2', '\x2', '\x8A', '\x8B', '\a', '\x15', '\x2', '\x2', '\x8B', '\x8C', 
		'\x5', '(', '\x15', '\x2', '\x8C', '\x8D', '\a', '\x16', '\x2', '\x2', 
		'\x8D', '\x11', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\a', '\x5', 
		'\x2', '\x2', '\x8F', '\x90', '\a', '\x15', '\x2', '\x2', '\x90', '\x91', 
		'\x5', '\x14', '\v', '\x2', '\x91', '\x92', '\a', '\x16', '\x2', '\x2', 
		'\x92', '\x13', '\x3', '\x2', '\x2', '\x2', '\x93', '\x94', '\b', '\v', 
		'\x1', '\x2', '\x94', '\x95', '\x5', '\x16', '\f', '\x2', '\x95', '\x9C', 
		'\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\f', '\x4', '\x2', '\x2', 
		'\x97', '\x98', '\x5', '\x1A', '\xE', '\x2', '\x98', '\x99', '\x5', '\x16', 
		'\f', '\x2', '\x99', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x96', 
		'\x3', '\x2', '\x2', '\x2', '\x9B', '\x9E', '\x3', '\x2', '\x2', '\x2', 
		'\x9C', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9D', '\x3', '\x2', 
		'\x2', '\x2', '\x9D', '\x15', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x9C', 
		'\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\b', '\f', '\x1', '\x2', 
		'\xA0', '\xA1', '\x5', '\x1E', '\x10', '\x2', '\xA1', '\xA8', '\x3', '\x2', 
		'\x2', '\x2', '\xA2', '\xA3', '\f', '\x4', '\x2', '\x2', '\xA3', '\xA4', 
		'\x5', '\x1C', '\xF', '\x2', '\xA4', '\xA5', '\x5', '\x1E', '\x10', '\x2', 
		'\xA5', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA2', '\x3', '\x2', 
		'\x2', '\x2', '\xA7', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA6', 
		'\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\x3', '\x2', '\x2', '\x2', 
		'\xA9', '\x17', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xA8', '\x3', '\x2', 
		'\x2', '\x2', '\xAB', '\xAC', '\x5', '\x14', '\v', '\x2', '\xAC', '\xAD', 
		'\x5', ',', '\x17', '\x2', '\xAD', '\xAE', '\x5', '\x18', '\r', '\x2', 
		'\xAE', '\xB1', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB1', '\x5', '\x14', 
		'\v', '\x2', '\xB0', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xAF', 
		'\x3', '\x2', '\x2', '\x2', '\xB1', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\xB2', '\xB3', '\t', '\x2', '\x2', '\x2', '\xB3', '\x1B', '\x3', '\x2', 
		'\x2', '\x2', '\xB4', '\xB5', '\t', '\x3', '\x2', '\x2', '\xB5', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\xB6', '\xB9', '\x5', ' ', '\x11', '\x2', 
		'\xB7', '\xB9', '\x5', '(', '\x15', '\x2', '\xB8', '\xB6', '\x3', '\x2', 
		'\x2', '\x2', '\xB8', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xB9', '\x1F', 
		'\x3', '\x2', '\x2', '\x2', '\xBA', '\xBE', '\x5', '\"', '\x12', '\x2', 
		'\xBB', '\xBE', '\x5', '$', '\x13', '\x2', '\xBC', '\xBE', '\x5', '&', 
		'\x14', '\x2', '\xBD', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xBB', 
		'\x3', '\x2', '\x2', '\x2', '\xBD', '\xBC', '\x3', '\x2', '\x2', '\x2', 
		'\xBE', '!', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC0', '\a', '!', '\x2', 
		'\x2', '\xC0', '#', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xC2', '\a', 
		'&', '\x2', '\x2', '\xC2', '%', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC4', 
		'\a', '$', '\x2', '\x2', '\xC4', '\'', '\x3', '\x2', '\x2', '\x2', '\xC5', 
		'\xC6', '\a', '%', '\x2', '\x2', '\xC6', ')', '\x3', '\x2', '\x2', '\x2', 
		'\xC7', '\xC8', '\a', '\x6', '\x2', '\x2', '\xC8', '\xC9', '\a', '%', 
		'\x2', '\x2', '\xC9', '+', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', 
		'\t', '\x4', '\x2', '\x2', '\xCB', '-', '\x3', '\x2', '\x2', '\x2', '\xCC', 
		'\xCD', '\x5', '*', '\x16', '\x2', '\xCD', '\xCE', '\a', '\x10', '\x2', 
		'\x2', '\xCE', '\xCF', '\x5', '\x30', '\x19', '\x2', '\xCF', '\xD5', '\x3', 
		'\x2', '\x2', '\x2', '\xD0', '\xD1', '\x5', '(', '\x15', '\x2', '\xD1', 
		'\xD2', '\a', '\x10', '\x2', '\x2', '\xD2', '\xD3', '\x5', '\x30', '\x19', 
		'\x2', '\xD3', '\xD5', '\x3', '\x2', '\x2', '\x2', '\xD4', '\xCC', '\x3', 
		'\x2', '\x2', '\x2', '\xD4', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xD5', 
		'/', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD9', '\x5', '\x32', '\x1A', 
		'\x2', '\xD7', '\xD9', '\x5', '\x46', '$', '\x2', '\xD8', '\xD6', '\x3', 
		'\x2', '\x2', '\x2', '\xD8', '\xD7', '\x3', '\x2', '\x2', '\x2', '\xD9', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xDE', '\x5', '\x14', '\v', 
		'\x2', '\xDB', '\xDE', '\x5', '\x18', '\r', '\x2', '\xDC', '\xDE', '\x5', 
		'\x1E', '\x10', '\x2', '\xDD', '\xDA', '\x3', '\x2', '\x2', '\x2', '\xDD', 
		'\xDB', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDC', '\x3', '\x2', '\x2', 
		'\x2', '\xDE', '\x33', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xE0', '\a', 
		'\"', '\x2', '\x2', '\xE0', '\xE1', '\a', '\x15', '\x2', '\x2', '\xE1', 
		'\xE2', '\x5', '\x36', '\x1C', '\x2', '\xE2', '\xE3', '\a', '\x16', '\x2', 
		'\x2', '\xE3', '\xE5', '\x5', '\n', '\x6', '\x2', '\xE4', '\xE6', '\x5', 
		'\x38', '\x1D', '\x2', '\xE5', '\xE4', '\x3', '\x2', '\x2', '\x2', '\xE5', 
		'\xE6', '\x3', '\x2', '\x2', '\x2', '\xE6', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\xE7', '\xE8', '\x5', '\x18', '\r', '\x2', '\xE8', '\x37', '\x3', 
		'\x2', '\x2', '\x2', '\xE9', '\xEA', '\a', '#', '\x2', '\x2', '\xEA', 
		'\xEB', '\x5', '\n', '\x6', '\x2', '\xEB', '\x39', '\x3', '\x2', '\x2', 
		'\x2', '\xEC', '\xEF', '\x5', '<', '\x1F', '\x2', '\xED', '\xEF', '\x5', 
		'@', '!', '\x2', '\xEE', '\xEC', '\x3', '\x2', '\x2', '\x2', '\xEE', '\xED', 
		'\x3', '\x2', '\x2', '\x2', '\xEF', ';', '\x3', '\x2', '\x2', '\x2', '\xF0', 
		'\xF1', '\a', '\t', '\x2', '\x2', '\xF1', '\xF2', '\a', '\x15', '\x2', 
		'\x2', '\xF2', '\xF3', '\x5', '>', ' ', '\x2', '\xF3', '\xF4', '\a', '\x16', 
		'\x2', '\x2', '\xF4', '\xF5', '\x5', '\n', '\x6', '\x2', '\xF5', '=', 
		'\x3', '\x2', '\x2', '\x2', '\xF6', '\xF7', '\x5', '\x18', '\r', '\x2', 
		'\xF7', '?', '\x3', '\x2', '\x2', '\x2', '\xF8', '\xF9', '\a', '\b', '\x2', 
		'\x2', '\xF9', '\xFB', '\a', '\x15', '\x2', '\x2', '\xFA', '\xFC', '\x5', 
		'.', '\x18', '\x2', '\xFB', '\xFA', '\x3', '\x2', '\x2', '\x2', '\xFB', 
		'\xFC', '\x3', '\x2', '\x2', '\x2', '\xFC', '\xFD', '\x3', '\x2', '\x2', 
		'\x2', '\xFD', '\xFE', '\a', '\xF', '\x2', '\x2', '\xFE', '\xFF', '\x5', 
		'\x42', '\"', '\x2', '\xFF', '\x101', '\a', '\xF', '\x2', '\x2', '\x100', 
		'\x102', '\x5', '\x44', '#', '\x2', '\x101', '\x100', '\x3', '\x2', '\x2', 
		'\x2', '\x101', '\x102', '\x3', '\x2', '\x2', '\x2', '\x102', '\x103', 
		'\x3', '\x2', '\x2', '\x2', '\x103', '\x104', '\a', '\x16', '\x2', '\x2', 
		'\x104', '\x105', '\x5', '\n', '\x6', '\x2', '\x105', '\x41', '\x3', '\x2', 
		'\x2', '\x2', '\x106', '\x107', '\x5', '\x18', '\r', '\x2', '\x107', '\x43', 
		'\x3', '\x2', '\x2', '\x2', '\x108', '\x109', '\x5', '(', '\x15', '\x2', 
		'\x109', '\x10A', '\a', '\x10', '\x2', '\x2', '\x10A', '\x10B', '\x5', 
		'\x30', '\x19', '\x2', '\x10B', '\x45', '\x3', '\x2', '\x2', '\x2', '\x10C', 
		'\x10D', '\a', '\n', '\x2', '\x2', '\x10D', '\x10E', '\x5', 'H', '%', 
		'\x2', '\x10E', '\x10F', '\a', '\v', '\x2', '\x2', '\x10F', 'G', '\x3', 
		'\x2', '\x2', '\x2', '\x110', '\x112', '\a', '\xE', '\x2', '\x2', '\x111', 
		'\x110', '\x3', '\x2', '\x2', '\x2', '\x112', '\x115', '\x3', '\x2', '\x2', 
		'\x2', '\x113', '\x111', '\x3', '\x2', '\x2', '\x2', '\x113', '\x114', 
		'\x3', '\x2', '\x2', '\x2', '\x114', '\x117', '\x3', '\x2', '\x2', '\x2', 
		'\x115', '\x113', '\x3', '\x2', '\x2', '\x2', '\x116', '\x118', '\x5', 
		'J', '&', '\x2', '\x117', '\x116', '\x3', '\x2', '\x2', '\x2', '\x117', 
		'\x118', '\x3', '\x2', '\x2', '\x2', '\x118', '\x121', '\x3', '\x2', '\x2', 
		'\x2', '\x119', '\x11B', '\a', '\xE', '\x2', '\x2', '\x11A', '\x119', 
		'\x3', '\x2', '\x2', '\x2', '\x11B', '\x11C', '\x3', '\x2', '\x2', '\x2', 
		'\x11C', '\x11A', '\x3', '\x2', '\x2', '\x2', '\x11C', '\x11D', '\x3', 
		'\x2', '\x2', '\x2', '\x11D', '\x11E', '\x3', '\x2', '\x2', '\x2', '\x11E', 
		'\x120', '\x5', 'J', '&', '\x2', '\x11F', '\x11A', '\x3', '\x2', '\x2', 
		'\x2', '\x120', '\x123', '\x3', '\x2', '\x2', '\x2', '\x121', '\x11F', 
		'\x3', '\x2', '\x2', '\x2', '\x121', '\x122', '\x3', '\x2', '\x2', '\x2', 
		'\x122', '\x127', '\x3', '\x2', '\x2', '\x2', '\x123', '\x121', '\x3', 
		'\x2', '\x2', '\x2', '\x124', '\x126', '\a', '\xE', '\x2', '\x2', '\x125', 
		'\x124', '\x3', '\x2', '\x2', '\x2', '\x126', '\x129', '\x3', '\x2', '\x2', 
		'\x2', '\x127', '\x125', '\x3', '\x2', '\x2', '\x2', '\x127', '\x128', 
		'\x3', '\x2', '\x2', '\x2', '\x128', 'I', '\x3', '\x2', '\x2', '\x2', 
		'\x129', '\x127', '\x3', '\x2', '\x2', '\x2', '\x12A', '\x12B', '\x5', 
		'\x32', '\x1A', '\x2', '\x12B', 'K', '\x3', '\x2', '\x2', '\x2', '\x1C', 
		'O', 'S', 'X', '\x62', 'g', 'n', 'u', '|', '\x82', '\x9C', '\xA8', '\xB0', 
		'\xB8', '\xBD', '\xD4', '\xD8', '\xDD', '\xE5', '\xEE', '\xFB', '\x101', 
		'\x113', '\x117', '\x11C', '\x121', '\x127',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
