//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JavaScriptLexer.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class JavaScriptLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		MULTI_LINE_COMMENT=1, SINGLE_LINE_COMMENT=2, CONSOLE_LOG=3, VAR=4, ASSIGN=5, 
		PLUS=6, MINUS=7, DIVIDE=8, MULTIPLY=9, OPEN_PAREN=10, CLOSE_PAREN=11, 
		BOOLEAN=12, NUMBER=13, IDENTIFIER=14, STRING=15, EOL=16, WHITE_SPACES=17;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"MULTI_LINE_COMMENT", "SINGLE_LINE_COMMENT", "CONSOLE_LOG", "VAR", "ASSIGN", 
		"PLUS", "MINUS", "DIVIDE", "MULTIPLY", "OPEN_PAREN", "CLOSE_PAREN", "BOOLEAN", 
		"NUMBER", "INTEGER_NUMBER", "IDENTIFIER", "STRING", "DoubleStringCharacter", 
		"SingleStringCharacter", "SingleEscapeCharacter", "LineContinuation", 
		"EOL", "WHITE_SPACES"
	};


	public JavaScriptLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public JavaScriptLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, "'console.log'", "'var'", "'='", "'+'", "'-'", "'/'", 
		"'*'", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "MULTI_LINE_COMMENT", "SINGLE_LINE_COMMENT", "CONSOLE_LOG", "VAR", 
		"ASSIGN", "PLUS", "MINUS", "DIVIDE", "MULTIPLY", "OPEN_PAREN", "CLOSE_PAREN", 
		"BOOLEAN", "NUMBER", "IDENTIFIER", "STRING", "EOL", "WHITE_SPACES"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "JavaScriptLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static JavaScriptLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x13', '\xC5', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\a', '\x2', '\x34', '\n', '\x2', '\f', 
		'\x2', '\xE', '\x2', '\x37', '\v', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\a', '\x3', '\x42', '\n', '\x3', '\f', '\x3', 
		'\xE', '\x3', '\x45', '\v', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x5', '\r', 'p', '\n', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\a', '\xE', 'v', '\n', '\xE', '\f', 
		'\xE', '\xE', '\xE', 'y', '\v', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\a', '\xE', '~', '\n', '\xE', '\f', '\xE', '\xE', '\xE', '\x81', 
		'\v', '\xE', '\x3', '\xE', '\x5', '\xE', '\x84', '\n', '\xE', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\a', '\xF', '\x89', '\n', '\xF', '\f', '\xF', 
		'\xE', '\xF', '\x8C', '\v', '\xF', '\x5', '\xF', '\x8E', '\n', '\xF', 
		'\x3', '\x10', '\x3', '\x10', '\a', '\x10', '\x92', '\n', '\x10', '\f', 
		'\x10', '\xE', '\x10', '\x95', '\v', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\a', '\x11', '\x99', '\n', '\x11', '\f', '\x11', '\xE', '\x11', '\x9C', 
		'\v', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\a', '\x11', 
		'\xA1', '\n', '\x11', '\f', '\x11', '\xE', '\x11', '\xA4', '\v', '\x11', 
		'\x3', '\x11', '\x5', '\x11', '\xA7', '\n', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', '\xAD', '\n', '\x12', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x5', '\x13', 
		'\xB3', '\n', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x16', '\x6', '\x16', '\xBB', '\n', '\x16', 
		'\r', '\x16', '\xE', '\x16', '\xBC', '\x3', '\x17', '\x6', '\x17', '\xC0', 
		'\n', '\x17', '\r', '\x17', '\xE', '\x17', '\xC1', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x35', '\x2', '\x18', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', 
		'\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', 
		'\x1D', '\x2', '\x1F', '\x10', '!', '\x11', '#', '\x2', '%', '\x2', '\'', 
		'\x2', ')', '\x2', '+', '\x12', '-', '\x13', '\x3', '\x2', '\f', '\x5', 
		'\x2', '\f', '\f', '\xF', '\xF', '\x202A', '\x202B', '\x3', '\x2', '\x32', 
		';', '\x4', '\x2', '\x32', ';', '\x61', '\x61', '\x3', '\x2', '\x33', 
		';', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', 
		'\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', 
		'\f', '\f', '\xF', '\xF', '$', '$', '^', '^', '\x6', '\x2', '\f', '\f', 
		'\xF', '\xF', ')', ')', '^', '^', '\v', '\x2', '$', '$', ')', ')', '^', 
		'^', '\x64', '\x64', 'h', 'h', 'p', 'p', 't', 't', 'v', 'v', 'x', 'x', 
		'\x6', '\x2', '\v', '\v', '\r', '\xE', '\"', '\"', '\xA2', '\xA2', '\x2', 
		'\xD2', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x3', '/', 
		'\x3', '\x2', '\x2', '\x2', '\x5', '=', '\x3', '\x2', '\x2', '\x2', '\a', 
		'H', '\x3', '\x2', '\x2', '\x2', '\t', 'T', '\x3', '\x2', '\x2', '\x2', 
		'\v', 'X', '\x3', '\x2', '\x2', '\x2', '\r', 'Z', '\x3', '\x2', '\x2', 
		'\x2', '\xF', '\\', '\x3', '\x2', '\x2', '\x2', '\x11', '^', '\x3', '\x2', 
		'\x2', '\x2', '\x13', '`', '\x3', '\x2', '\x2', '\x2', '\x15', '\x62', 
		'\x3', '\x2', '\x2', '\x2', '\x17', '\x64', '\x3', '\x2', '\x2', '\x2', 
		'\x19', 'o', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x83', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x8F', 
		'\x3', '\x2', '\x2', '\x2', '!', '\xA6', '\x3', '\x2', '\x2', '\x2', '#', 
		'\xAC', '\x3', '\x2', '\x2', '\x2', '%', '\xB2', '\x3', '\x2', '\x2', 
		'\x2', '\'', '\xB4', '\x3', '\x2', '\x2', '\x2', ')', '\xB6', '\x3', '\x2', 
		'\x2', '\x2', '+', '\xBA', '\x3', '\x2', '\x2', '\x2', '-', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', '/', '\x30', '\a', '\x31', '\x2', '\x2', '\x30', 
		'\x31', '\a', ',', '\x2', '\x2', '\x31', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x32', '\x34', '\v', '\x2', '\x2', '\x2', '\x33', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\x34', '\x37', '\x3', '\x2', '\x2', '\x2', '\x35', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\x35', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x36', '\x38', '\x3', '\x2', '\x2', '\x2', '\x37', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x38', '\x39', '\a', ',', '\x2', '\x2', '\x39', 
		':', '\a', '\x31', '\x2', '\x2', ':', ';', '\x3', '\x2', '\x2', '\x2', 
		';', '<', '\b', '\x2', '\x2', '\x2', '<', '\x4', '\x3', '\x2', '\x2', 
		'\x2', '=', '>', '\a', '\x31', '\x2', '\x2', '>', '?', '\a', '\x31', '\x2', 
		'\x2', '?', '\x43', '\x3', '\x2', '\x2', '\x2', '@', '\x42', '\n', '\x2', 
		'\x2', '\x2', '\x41', '@', '\x3', '\x2', '\x2', '\x2', '\x42', '\x45', 
		'\x3', '\x2', '\x2', '\x2', '\x43', '\x41', '\x3', '\x2', '\x2', '\x2', 
		'\x43', '\x44', '\x3', '\x2', '\x2', '\x2', '\x44', '\x46', '\x3', '\x2', 
		'\x2', '\x2', '\x45', '\x43', '\x3', '\x2', '\x2', '\x2', '\x46', 'G', 
		'\b', '\x3', '\x2', '\x2', 'G', '\x6', '\x3', '\x2', '\x2', '\x2', 'H', 
		'I', '\a', '\x65', '\x2', '\x2', 'I', 'J', '\a', 'q', '\x2', '\x2', 'J', 
		'K', '\a', 'p', '\x2', '\x2', 'K', 'L', '\a', 'u', '\x2', '\x2', 'L', 
		'M', '\a', 'q', '\x2', '\x2', 'M', 'N', '\a', 'n', '\x2', '\x2', 'N', 
		'O', '\a', 'g', '\x2', '\x2', 'O', 'P', '\a', '\x30', '\x2', '\x2', 'P', 
		'Q', '\a', 'n', '\x2', '\x2', 'Q', 'R', '\a', 'q', '\x2', '\x2', 'R', 
		'S', '\a', 'i', '\x2', '\x2', 'S', '\b', '\x3', '\x2', '\x2', '\x2', 'T', 
		'U', '\a', 'x', '\x2', '\x2', 'U', 'V', '\a', '\x63', '\x2', '\x2', 'V', 
		'W', '\a', 't', '\x2', '\x2', 'W', '\n', '\x3', '\x2', '\x2', '\x2', 'X', 
		'Y', '\a', '?', '\x2', '\x2', 'Y', '\f', '\x3', '\x2', '\x2', '\x2', 'Z', 
		'[', '\a', '-', '\x2', '\x2', '[', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'\\', ']', '\a', '/', '\x2', '\x2', ']', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '^', '_', '\a', '\x31', '\x2', '\x2', '_', '\x12', '\x3', '\x2', 
		'\x2', '\x2', '`', '\x61', '\a', ',', '\x2', '\x2', '\x61', '\x14', '\x3', 
		'\x2', '\x2', '\x2', '\x62', '\x63', '\a', '*', '\x2', '\x2', '\x63', 
		'\x16', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', '+', '\x2', 
		'\x2', '\x65', '\x18', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', '\a', 
		'v', '\x2', '\x2', 'g', 'h', '\a', 't', '\x2', '\x2', 'h', 'i', '\a', 
		'w', '\x2', '\x2', 'i', 'p', '\a', 'g', '\x2', '\x2', 'j', 'k', '\a', 
		'h', '\x2', '\x2', 'k', 'l', '\a', '\x63', '\x2', '\x2', 'l', 'm', '\a', 
		'n', '\x2', '\x2', 'm', 'n', '\a', 'u', '\x2', '\x2', 'n', 'p', '\a', 
		'g', '\x2', '\x2', 'o', '\x66', '\x3', '\x2', '\x2', '\x2', 'o', 'j', 
		'\x3', '\x2', '\x2', '\x2', 'p', '\x1A', '\x3', '\x2', '\x2', '\x2', 'q', 
		'r', '\x5', '\x1D', '\xF', '\x2', 'r', 's', '\a', '\x30', '\x2', '\x2', 
		's', 'w', '\t', '\x3', '\x2', '\x2', 't', 'v', '\t', '\x4', '\x2', '\x2', 
		'u', 't', '\x3', '\x2', '\x2', '\x2', 'v', 'y', '\x3', '\x2', '\x2', '\x2', 
		'w', 'u', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\x3', '\x2', '\x2', '\x2', 
		'x', '\x84', '\x3', '\x2', '\x2', '\x2', 'y', 'w', '\x3', '\x2', '\x2', 
		'\x2', 'z', '{', '\a', '\x30', '\x2', '\x2', '{', '\x7F', '\t', '\x3', 
		'\x2', '\x2', '|', '~', '\t', '\x4', '\x2', '\x2', '}', '|', '\x3', '\x2', 
		'\x2', '\x2', '~', '\x81', '\x3', '\x2', '\x2', '\x2', '\x7F', '}', '\x3', 
		'\x2', '\x2', '\x2', '\x7F', '\x80', '\x3', '\x2', '\x2', '\x2', '\x80', 
		'\x84', '\x3', '\x2', '\x2', '\x2', '\x81', '\x7F', '\x3', '\x2', '\x2', 
		'\x2', '\x82', '\x84', '\x5', '\x1D', '\xF', '\x2', '\x83', 'q', '\x3', 
		'\x2', '\x2', '\x2', '\x83', 'z', '\x3', '\x2', '\x2', '\x2', '\x83', 
		'\x82', '\x3', '\x2', '\x2', '\x2', '\x84', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', '\x85', '\x8E', '\a', '\x32', '\x2', '\x2', '\x86', '\x8A', '\t', 
		'\x5', '\x2', '\x2', '\x87', '\x89', '\t', '\x4', '\x2', '\x2', '\x88', 
		'\x87', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', '\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\x3', 
		'\x2', '\x2', '\x2', '\x8B', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x8C', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x85', '\x3', '\x2', '\x2', 
		'\x2', '\x8D', '\x86', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x1E', '\x3', 
		'\x2', '\x2', '\x2', '\x8F', '\x93', '\t', '\x6', '\x2', '\x2', '\x90', 
		'\x92', '\t', '\a', '\x2', '\x2', '\x91', '\x90', '\x3', '\x2', '\x2', 
		'\x2', '\x92', '\x95', '\x3', '\x2', '\x2', '\x2', '\x93', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '\x93', '\x94', '\x3', '\x2', '\x2', '\x2', '\x94', 
		' ', '\x3', '\x2', '\x2', '\x2', '\x95', '\x93', '\x3', '\x2', '\x2', 
		'\x2', '\x96', '\x9A', '\a', '$', '\x2', '\x2', '\x97', '\x99', '\x5', 
		'#', '\x12', '\x2', '\x98', '\x97', '\x3', '\x2', '\x2', '\x2', '\x99', 
		'\x9C', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x98', '\x3', '\x2', '\x2', 
		'\x2', '\x9A', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9D', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x9D', 
		'\xA7', '\a', '$', '\x2', '\x2', '\x9E', '\xA2', '\a', ')', '\x2', '\x2', 
		'\x9F', '\xA1', '\x5', '%', '\x13', '\x2', '\xA0', '\x9F', '\x3', '\x2', 
		'\x2', '\x2', '\xA1', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA0', 
		'\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\x3', '\x2', '\x2', '\x2', 
		'\xA3', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA2', '\x3', '\x2', 
		'\x2', '\x2', '\xA5', '\xA7', '\a', ')', '\x2', '\x2', '\xA6', '\x96', 
		'\x3', '\x2', '\x2', '\x2', '\xA6', '\x9E', '\x3', '\x2', '\x2', '\x2', 
		'\xA7', '\"', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xAD', '\n', '\b', 
		'\x2', '\x2', '\xA9', '\xAA', '\a', '^', '\x2', '\x2', '\xAA', '\xAD', 
		'\x5', '\'', '\x14', '\x2', '\xAB', '\xAD', '\x5', ')', '\x15', '\x2', 
		'\xAC', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xA9', '\x3', '\x2', 
		'\x2', '\x2', '\xAC', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAD', '$', 
		'\x3', '\x2', '\x2', '\x2', '\xAE', '\xB3', '\n', '\t', '\x2', '\x2', 
		'\xAF', '\xB0', '\a', '^', '\x2', '\x2', '\xB0', '\xB3', '\x5', '\'', 
		'\x14', '\x2', '\xB1', '\xB3', '\x5', ')', '\x15', '\x2', '\xB2', '\xAE', 
		'\x3', '\x2', '\x2', '\x2', '\xB2', '\xAF', '\x3', '\x2', '\x2', '\x2', 
		'\xB2', '\xB1', '\x3', '\x2', '\x2', '\x2', '\xB3', '&', '\x3', '\x2', 
		'\x2', '\x2', '\xB4', '\xB5', '\t', '\n', '\x2', '\x2', '\xB5', '(', '\x3', 
		'\x2', '\x2', '\x2', '\xB6', '\xB7', '\a', '^', '\x2', '\x2', '\xB7', 
		'\xB8', '\t', '\x2', '\x2', '\x2', '\xB8', '*', '\x3', '\x2', '\x2', '\x2', 
		'\xB9', '\xBB', '\t', '\x2', '\x2', '\x2', '\xBA', '\xB9', '\x3', '\x2', 
		'\x2', '\x2', '\xBB', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBA', 
		'\x3', '\x2', '\x2', '\x2', '\xBC', '\xBD', '\x3', '\x2', '\x2', '\x2', 
		'\xBD', ',', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xC0', '\t', '\v', '\x2', 
		'\x2', '\xBF', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC1', '\x3', 
		'\x2', '\x2', '\x2', '\xC1', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xC1', 
		'\xC2', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC3', '\x3', '\x2', '\x2', 
		'\x2', '\xC3', '\xC4', '\b', '\x17', '\x2', '\x2', '\xC4', '.', '\x3', 
		'\x2', '\x2', '\x2', '\x13', '\x2', '\x35', '\x43', 'o', 'w', '\x7F', 
		'\x83', '\x8A', '\x8D', '\x93', '\x9A', '\xA2', '\xA6', '\xAC', '\xB2', 
		'\xBC', '\xC1', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
